# Generated by Django 2.1.5 on 2020-12-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.ImageField(upload_to='pictures'),
        ),
    ]
