# Generated by Django 3.1.4 on 2020-12-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201219_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.FileField(upload_to='uploads/% Y/% m/% d/'),
        ),
    ]
